#!/bin/bash

for BRANCH in $(git branch --merged | awk '{print $1}' | egrep '(bugfix|feature|hotfix)'); do
  echo "* delete: ${BRANCH}"
  git branch -d "${BRANCH}" && \
    (git push --delete "${USER}" "${BRANCH}" || true)
done

